# .github/release.yml

changelog:
  exclude:
    labels:
      - documentation
      - release
      - tests
      - backmerge
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: New Features 🎉
      labels:
        - minor
    - title: Bug Fixes
      labels:
        - patch
    - title: Other Changes
      labels:
        - "*"